[package]
name = "strpipe"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.22", features = ["std"] }
nix = { version = "0.29.0", features = ["fs"] }
thiserror = "1.0.63"
